#!/bin/bash

set -e

rm -rf ./immunity_controller/geo/tests/.pytest_cache \
       ./immunity_controller/config/tests/.pytest_cache/ \
       ./immunity_controller/connection/tests/.pytest_cache/ \
       ./immunity_controller/.pytest_cache/ \
       ./tests/immunity22/sample_geo/.pytest_cache \
       ./tests/.pytest_cache \
       ./tests/immunity22/.pytest_cache/ \
       ./htmlcov/ 2> /dev/null || true

immunity-qa-check \
  --csslinter \
  --jslinter \
  --migrations-to-ignore "12 0 0 4" \
  --migration-path "./immunity_controller/config/migrations
                  ./immunity_controller/connection/migrations
                  ./immunity_controller/geo/migrations
                  ./immunity_controller/pki/migrations
                  ./immunity_controller/subnet_division/migrations"

echo ''
echo 'Running checks for SAMPLE_APP'
SAMPLE_APP=1 immunity-qa-check \
  --skip-isort \
  --skip-flake8 \
  --skip-black \
  --skip-checkendline \
  --skip-checkcommit \
  --migration-path "./tests/immunity22/sample_config/migrations/
                    ./tests/immunity22/sample_pki/migrations/
                    ./tests/immunity22/sample_connection/migrations/
                    ./tests/immunity22/sample_geo/migrations/
                    ./tests/immunity22/sample_subnet_division/migrations/"
